# This is a custom module we've made.  
# Modules are files full of code that you can import into your programs.
# This one teaches our turtle to draw various shapes.

import turtle


def draw_circle(turtle, color, size, x, y):
  turtle.penup()
  turtle.color(color)
  turtle.fillcolor(color)
  turtle.goto(x,y)
  turtle.pendown()
  turtle.begin_fill()
  turtle.circle(size)
  turtle.end_fill()
    
def draw_triangle(turtle, color, size, x, y):
  turtle.penup()
  turtle.color(color)
  turtle.fillcolor(color)
  turtle.goto(x,y)
  turtle.pendown()
  turtle.begin_fill()
  for i in range (3):
    turtle.forward(size*3)
    turtle.left(120)
  turtle.end_fill()
  turtle.setheading(0)
    
def draw_square(turtle, color, size, x, y):
  turtle.penup()
  turtle.color(color)
  turtle.fillcolor(color)
  turtle.goto(x,y)
  turtle.pendown()
  turtle.begin_fill()
  for i in range (4):
    turtle.forward(size*2)
    turtle.left(90)
  turtle.end_fill()
  turtle.setheading(0)

def draw_square_outline(turtle, color, size, x, y):
  turtle.penup()
  turtle.color(color)
  turtle.goto(x,y)
  turtle.pendown()
  for i in range (4):
    turtle.forward(size*2)
    turtle.left(90)
  turtle.setheading(0)

def draw_rectangle_outline(turtle, color, size, x, y):
  turtle.penup()
  turtle.color(color)
  turtle.goto(x,y)
  turtle.pendown()
  for i in range (2):
    turtle.forward(size*4)
    turtle.left(90)
    turtle.forward(size*2)
    turtle.left(90)
  turtle.setheading(0)
    
def draw_bricks(x, y):
  turtle.hideturtle()
  turtle.penup()
  turtle.goto(x,y)
  turtle.pendown()
  turtle.forward(15)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(15)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(55)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(55)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(70)
  turtle.right(90)
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(70)
  turtle.right(90)
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(60)
  turtle.left(90)
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(70)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(30)
  turtle.right(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.penup()

def draw_star(turtle, color, size, x, y):
  turtle.penup()
  turtle.color(color)
  turtle.fillcolor(color)
  turtle.goto(x,y)
  turtle.pendown()
  turtle.begin_fill()
  turtle.right(144)
  for i in range(5):
    turtle.forward(size*2)
    turtle.right(144)
    turtle.forward(size*2)
  turtle.end_fill()
  turtle.setheading(0)

def draw_mushroom(x, y):
  turtle.goto(x,y)
  turtle.pendown()
  turtle.color("orange")
  turtle.begin_fill()
  turtle.forward(25)
  turtle.circle(15, 140)
  turtle.forward(25)
  turtle.circle(15, 80)
  turtle.forward(25)
  turtle.circle(15, 140)
  turtle.forward(18)
  turtle.end_fill()
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.color("white")
  turtle.begin_fill()
  turtle.forward(7.5)
  turtle.circle(15, 180)
  turtle.forward(15)
  turtle.circle(15, 180)
  turtle.forward(15)
  turtle.end_fill()
  turtle.circle(15, 180)
  turtle.forward(7.5)
  turtle.penup()
  turtle.left(90)
  turtle.forward(50)
  turtle.left(90)
  turtle.forward(17)
  turtle.pendown()
  turtle.color("red")
  turtle.begin_fill()
  turtle.circle(7.5, 360)
  turtle.end_fill()
  turtle.penup()
  turtle.right(180)
  turtle.forward(16)
  turtle.left(90)
  turtle.forward(7.5)
  turtle.pendown()
  turtle.begin_fill()
  turtle.circle(-7.5, 360)
  turtle.end_fill()
  turtle.penup()
  turtle.right(180)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(20)
  turtle.pendown()
  turtle.begin_fill()
  turtle.circle(7.5, 360)
  turtle.end_fill()
  turtle.penup()
 
def draw_goomba(x, y):
  turtle.goto(x,y)
  turtle.pendown()
  turtle.color("brown")
  turtle.begin_fill()
  turtle.forward(25)
  turtle.circle(15, 140)
  turtle.forward(25)
  turtle.circle(15, 80)
  turtle.forward(25)
  turtle.circle(15, 140)
  turtle.forward(18)
  turtle.end_fill()
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.backward(2.5)
  turtle.color("beige")
  turtle.begin_fill()
  turtle.forward(7.5)
  turtle.circle(15, 180)
  turtle.forward(15)
  turtle.circle(15, 180)
  turtle.forward(15)
  turtle.end_fill()
  turtle.penup()
  turtle.left(90)
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(13)
  turtle.pendown()
  turtle.right(20)
  turtle.color("black")
  turtle.begin_fill()
  turtle.circle(5, 180)
  turtle.forward(10)
  turtle.circle(5, 180)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.left(20)
  turtle.right(180)
  turtle.forward(45)
  turtle.pendown()
  turtle.begin_fill()
  turtle.circle(-7, 180)
  turtle.forward(10)
  turtle.circle(-7, 180)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.left(90)
  turtle.forward(40)
  turtle.left(35)
  turtle.pendown()
  turtle.pensize(4)
  turtle.circle(8,120)
  turtle.circle(-11, 130)
  turtle.circle(8, 130)
  turtle.penup()
  turtle.pensize(1)
  turtle.right(180)
  turtle.circle(-8, 65)
  turtle.right(90)
  turtle.pendown()
  turtle.color("white")
  turtle.begin_fill()
  turtle.forward(20)
  turtle.left(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.left(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(180)
  turtle.pendown()
  turtle.color("black")
  turtle.begin_fill()
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.end_fill()
  turtle.penup()
  turtle.right(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(10)
  turtle.right(180)
  turtle.pendown()
  turtle.color("white")
  turtle.begin_fill()
  turtle.forward(20)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.right(180)
  turtle.pendown()
  turtle.color("black")
  turtle.begin_fill()
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.end_fill()
  turtle.penup()

def draw_mario(x, y):
  turtle.goto(x, y)
  turtle.setheading(0)
  turtle.pendown()
  turtle.color("red")
  turtle.begin_fill()
  turtle.forward(40)
  turtle.left(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(15)
  turtle.right(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(20)
  turtle.end_fill()
  turtle.color("beige")
  turtle.begin_fill()
  turtle.forward(25)
  turtle.left(90)
  turtle.forward(30)
  turtle.left(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.end_fill()
  turtle.left(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.color("black")
  turtle.begin_fill()
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.right(180)
  turtle.forward(15)
  turtle.right(90)
  turtle.backward(10)
  turtle.pendown()
  turtle.color("brown")
  turtle.begin_fill()
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.pendown()
  turtle.color("red")
  turtle.begin_fill()
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(10)
  turtle.left(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(15)
  turtle.left(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.end_fill()
  turtle.left(90)
  turtle.color("brown")
  turtle.begin_fill()
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.forward(5)
  turtle.left(90)
  turtle.end_fill()
  turtle.penup()
  turtle.forward(10)
  turtle.left(90)
  turtle.pendown()
  turtle.begin_fill()
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(10)
  turtle.end_fill()
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.color('beige')
  turtle.begin_fill()
  turtle.left(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.end_fill()
  turtle.penup()
  turtle.right(90)
  turtle.forward(20)
  turtle.pendown()
  turtle.left(90)
  turtle.color("black")
  turtle.begin_fill()
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(10)
  turtle.end_fill()
  turtle.penup()
  turtle.forward(15)
  turtle.pendown()
  turtle.begin_fill()
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.right(90)
  turtle.forward(10)
  turtle.right(90)
  turtle.forward(5)
  turtle.end_fill()
  turtle.penup()

